### ISSUE TITLE
Using "stream-webrtc-android-1.1.2.aar" show NoSuchMethodError

### ISSUE THREAD

**Issue by ed3c** [GetStream/webrtc-android#163]
I download the [stream-webrtc-android-1.1.2.aar](https://repo1.maven.org/maven2/io/getstream/stream-webrtc-android/1.1.2/) and implement with grade
> implementation files('libs/libwebrtc.aar')

however, there is no such method "getDisableIpv6()". This is a method in java. 
```
java -version
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
```
We have a web rtc M89 to make call with Android & IOS. Testing upgrade each web rtc version is needed.
Should I get through error method "getDisableIpv6" or there is other way to do this. 

I haven't try build web rtc with my own. My current thought is upgrade my project and using the web rtc with local module without implement .aar

If you have any suggestions, I would be very grateful :)

### org.webrtc.Logging

> PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
> WebRtcAudioUtils: setWebRtcBasedAutomaticGainControl() is deprecated
> WebRtcAudioRecord: Set error callback
> WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
> WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
> JavaAudioDeviceModule: createAudioDeviceModule
> JavaAudioDeviceModule: HW NS will be used.
> JavaAudioDeviceModule: HW AEC will be used.
> WebRtcAudioEffectsExternal: ctor@[name=pool-34-thread-1, id=1605]
> WebRtcAudioRecordExternal: ctor@[name=pool-34-thread-1, id=1605]
> WebRtcAudioTrackExternal: ctor@[name=pool-34-thread-1, id=1605]
> WebRtcAudioRecordExternal: enableBuiltInAEC(true)
> WebRtcAudioEffectsExternal: setAEC(true)
> WebRtcAudioRecordExternal: enableBuiltInNS(true)
> WebRtcAudioEffectsExternal: setNS(true)
> PeerConnectionFactory: onNetworkThreadReady
> PeerConnectionFactory: onSignalingThreadReady
> PeerConnectionFactory: onWorkerThreadReady

### System.err
```
java.lang.NoSuchMethodError: no non-static method "Lorg/webrtc/PeerConnection$RTCConfiguration;.getDisableIpv6()Z"
	at org.webrtc.PeerConnectionFactory.nativeCreatePeerConnection(Native Method)
	at org.webrtc.PeerConnectionFactory.createPeerConnectionInternal(PeerConnectionFactory.java:379)
	at org.webrtc.PeerConnectionFactory.createPeerConnection(PeerConnectionFactory.java:395)
	at awesomelab.trueme.rtc.RTCPeerConnectionClient.createPeerConnectionInternal(RTCPeerConnectionClient.java:599)
	at awesomelab.trueme.rtc.RTCPeerConnectionClient.access$500(RTCPeerConnectionClient.java:67)
	at awesomelab.trueme.rtc.RTCPeerConnectionClient$2.run(RTCPeerConnectionClient.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
#
# Fatal error in: ../../sdk/android/src/jni/jni_generator_helper.cc, line 59
# last system error: 0
# Check failed: !env->ExceptionCheck()
# error during GetMethodID: getDisableIpv6, ()Z
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19118 (pool-34-thread-), pid 15586 (com.fiziico.r2)
```

**Comment by varun-metacube** [comment]
@ed3c which lib you used for iOS, can you please share link ?

**Comment by ed3c** [comment]
stream-webrtc-android-1.1.2.aar using web rtc M118 need to update the code about rtc_peer_connection_client. Old method call by a new M118 will cause method not found. M118 is compatible with M89 depends on device version.
