### ISSUE TITLE
No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder

### ISSUE THREAD

**Issue by the-it-weirdo** [GetStream/webrtc-android#244]
Hello I am receiving this error:

`java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(long, org.webrtc.VideoCodecInfo) (tried Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder and Java_org_webrtc_SoftwareVideoDecoderFactory_nativeCreateDecoder__JLorg_webrtc_VideoCodecInfo_2) - is the library loaded, e.g. System.loadLibrary?
at org.webrtc.SoftwareVideoDecoderFactory.nativeCreateDecoder(Native Method)
at org.webrtc.SoftwareVideoDecoderFactory.createDecoder(SoftwareVideoDecoderFactory.java:29)
at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:43)`

I already tried `System.loadLibrary` path without any results. Any help/guidance/direction is appreciated.

**Comment by the-it-weirdo** [comment]
Version 1.3.4 solves it.
