### ISSUE TITLE
`VideoRenderer` throws `CalledFromWrongThreadException` when called

### ISSUE THREAD

**Issue by Iorvethe** [GetStream/webrtc-android#59]
Hi,

I am building an application that pulls a video stream from a server via WebRTC and displays it on the screen. The server uses `aiortc` which I believe doesn’t support ICE trickling so all ICE candidates are gathered before initiating the connection.

Now, the whole process of sending an offer, receiving an answer and establishing a connection seems to work fine. However, when I call `VideoRenderer` with a `VideoTrack` taken from `PeerConnection.Observer.onTrack`, it crashes with the following stacktrace:

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9758)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1959)
	at android.view.View.requestLayout(View.java:26281)
	at android.view.View.requestLayout(View.java:26281)
	at android.view.View.requestLayout(View.java:26281)
	at android.view.View.requestLayout(View.java:26281)
	at android.view.View.requestLayout(View.java:26281)
	at androidx.compose.ui.platform.AndroidComposeView.scheduleMeasureAndLayout(AndroidComposeView.android.kt:778)
	at androidx.compose.ui.platform.AndroidComposeView.onRequestMeasure(AndroidComposeView.android.kt:834)
	at androidx.compose.ui.node.Owner.onRequestMeasure$default(Owner.kt:155)
	at androidx.compose.ui.node.LayoutNode.requestRemeasure$ui_release(LayoutNode.kt:1053)
	at androidx.compose.ui.node.LayoutNode.requestRemeasure$ui_release$default(LayoutNode.kt:1050)
	at androidx.compose.ui.platform.AndroidViewsHandler.requestLayout(AndroidViewsHandler.android.kt:91)
	at android.view.View.requestLayout(View.java:26281)
	at android.view.View.requestLayout(View.java:26281)
	at io.getstream.webrtc.android.ui.VideoTextureViewRenderer.updateFrameData(VideoTextureViewRenderer.kt:161)
	at io.getstream.webrtc.android.ui.VideoTextureViewRenderer.onFrame(VideoTextureViewRenderer.kt:133)
```

I have also tried with a plain `VideoTextureViewRenderer` to no avail, this time the screen being black with the following log:

```
EglRenderer: Dropping frame - Not initialized or already released.
```

I believe it is an issue with my code, because the official example works no problem. Unfortunately, I cannot pinpoint it and, being on it for a few days, would like to ask if there is perhaps some prerequisite for `VideoRenderer` to work and where might these issues come from?

Thanks for your attention!

**Comment by UrielFrankel** [comment]
I had it and changed:
`private fun updateFrameData(videoFrame: VideoFrame) {
        if (!isFirstFrameRendered) {
            rendererEvents?.onFirstFrameRendered()
            isFirstFrameRendered = true
        }

        if (videoFrame.rotatedWidth != rotatedFrameWidth ||
            videoFrame.rotatedHeight != rotatedFrameHeight ||
            videoFrame.rotation != frameRotation
        ) {
            rotatedFrameWidth = videoFrame.rotatedWidth
            rotatedFrameHeight = videoFrame.rotatedHeight
            frameRotation = videoFrame.rotation

            post { requestLayout() }

            uiThreadHandler.post {
                rendererEvents?.onFrameResolutionChanged(
                    rotatedFrameWidth,
                    rotatedFrameHeight,
                    frameRotation
                )
            }
        }
    }`

**Comment by Iorvethe** [comment]
Thanks a lot for your help!

**Comment by DanielNovak** [comment]
Thanks @UrielFrankel for handling this and for making a PR! I am marking this as resolved and closing this issue.

**Comment by UrielFrankel** [comment]
btw if you want, I can help you making the surface renderer round as well - if you will give me a handle to opengl

**Comment by Iorvethe** [comment]
Hi!

Just to report that I had the time to try it out, and it works perfectly. Thanks again for that.

As for the surface renderer (if it was addressed to me, never mind if it wasn’t), thanks for your offer, that’s very kind of you! For the moment, our team has decided to stick with a full-screen render of the video stream (we don’t have a local one) and on it, rounded corners would be odd I think. So, we’ll keep the sharp corners for the time being.

Have a nice week!

**Comment by UrielFrankel** [comment]
I was meant to everyone :)
